# $OpenBSD$

COMMENT=		"Powerful Multilingual File Viewer"

DISTNAME=		${PKGNAME:C/[-\.]//g}
PKGNAME=		lv-4.51
CATEGORIES=		misc

HOMEPAGE=		http://www.ff.iij4u.or.jp/~nrt/lv/
MAINTAINER=		TAKAHASHI Kaoru <kaoru@kaisei.org>

# GPL
PERMIT_PACKAGE_CDROM=	Yes
PERMIT_PACKAGE_FTP=	Yes
PERMIT_DISTFILES_CDROM=	Yes
PERMIT_DISTFILES_FTP=	Yes

MASTER_SITES=		http://www.ff.iij4u.or.jp/~nrt/freeware/

CONFIGURE_STYLE=	GNU
#CONFIGURE_ARGS+=	${CONFIGURE_SHARED}

WRKSRC=			${WRKDIST}/src

.include <bsd.port.mk>
