# $OpenBSD: Makefile,v 1.9 2001/05/06 01:46:00 lebel Exp $

COMMENT=	"Simple autoresponder for qmai"

DISTNAME=	autorespond-2.0.5
HOMEPAGE=	http://inter7.com/index.php?page=development
CATEGORIES=	mail
MAINTAINER=	Camiel Dobbelaar <cd@sentia.nl>

PORTNAME=       autorespond
PORTVERSION=    2.0.5
CATEGORIES=     mail
MASTER_SITES=   http://www.inter7.com/devel/

PERMIT_PACKAGE_CDROM=	Yes
PERMIT_PACKAGE_FTP=	Yes
PERMIT_DISTFILES_CDROM=	Yes
PERMIT_DISTFILES_FTP=	Yes

.include <bsd.port.mk>
