# $OpenBSD$
# $FreeBSD: ports/devel/p5-Data-Dumper/Makefile,v 1.2 2004/12/01 11:42:51 tobez Exp $
# Original from: mat@FreeBSD.org

COMMENT=	"Stringified perl data structures, suitable for both printing and eval"

DISTNAME=	Data-Dumper-2.121
PKGNAME=	p5-${DISTNAME}
CATEGORIES=	devel perl5	

HOMEPAGE=	http://search.cpan.org/dist/Data-Dumper/

MAINTAINER=	TAKAHASHI Kaoru <kaoru@kaisei.org>

PERMIT_PACKAGE_CDROM=	Yes
PERMIT_PACKAGE_FTP=	Yes
PERMIT_DISTFILES_CDROM=	Yes
PERMIT_DISTFILES_FTP=	Yes

MASTER_SITES=		${MASTER_SITE_PERL_CPAN:=Data/}

CONFIGURE_STYLE=	perl

#NO_REGRESS=		Yes

.include <bsd.port.mk>
