COMMENT=	"Pagination for views of model queries"

DISTNAME=	will_paginate-2.2.2
PKGNAME=	ruby-${DISTNAME}
CATEGORIES=	textproc ruby

HOMEPAGE=	http://github.com/mislav/will_paginate/wikis

MAINTAINER=	TAKAHASHI Kaoru <kaoru@kaisei.org>

# mit
PERMIT_PACKAGE_CDROM=   Yes
PERMIT_PACKAGE_FTP=     Yes
PERMIT_DISTFILES_CDROM= Yes
PERMIT_DISTFILES_FTP=   Yes

#MASTER_SITES=   ${MASTER_SITE_RUBYFORGE:=mislav-will_paginate/}
MASTER_SITES=	  http://rubyforge.rubyuser.de/gems/

MODULES=                lang/ruby

CONFIGURE_STYLE=	ruby gem

.include <bsd.port.mk>
