# $OpenBSD$

COMMENT=	"Rails plugin for Japanese mobile-phones"

DISTNAME=	jpmobile-0.0.3
PKGNAME=	ruby-${DISTNAME}
CATEGORIES=	japanese www ruby

HOMEPAGE=	http://jpmobile-rails.org/

MAINTAINER=	kaoru@kaisei.org

# mit
PERMIT_PACKAGE_CDROM=   Yes
PERMIT_PACKAGE_FTP=     Yes
PERMIT_DISTFILES_CDROM= Yes
PERMIT_DISTFILES_FTP=   Yes

MASTER_SITES=   ${MASTER_SITE_RUBYFORGE:=jpmobile/}

MODULES=                lang/ruby

CONFIGURE_STYLE=	ruby gem

.include <bsd.port.mk>
