# $OpenBSD$
# $FreeBSD: ports/mail/p5-Mail-Audit-Attach/Makefile,v 1.10 2010/03/01 09:04:26 wen Exp $

COMMENT=	Mail::Audit plugin for attachment handling

DISTNAME=	Mail-Audit-Attach-0.96
CATEGORIES=	mail

HOMEPAGE=	http://search.cpan.org/dist/Mail-Audit-Attach

MAINTAINER=	TAKAHASHI Kaoru <kaoru@kaisei.org>

# GPL/Artistic licence
PERMIT_PACKAGE_CDROM=	Yes
PERMIT_PACKAGE_FTP=	Yes
PERMIT_DISTFILES_CDROM=	Yes
PERMIT_DISTFILES_FTP=	Yes

MODULES=		cpan

RUN_DEPENDS=	::mail/p5-Mail-Audit \
		::mail/p5-Mail-Tools

.include <bsd.port.mk>
