# $OpenBSD: $
# $FreeBSD: $
# Original from: Yuuki SAWADA <samy@goldmoon.org>

DISTNAME=		xlvns1-1.6b
CATEGORIES=     	emulators
HOMEPAGE=		http://leafbsd.denpa.org/

MAINTAINER=		kaoru@kaisei.org

PERMIT_PACKAGE_CDROM=	"Must get permit by Leaf"
PERMIT_PACKAGE_FTP=	"Must get permit by Leaf"
PERMIT_DISTFILES_CDROM=	"Must get permit by Leaf"
PERMIT_DISTFILES_FTP=	"Must get permit by Leaf"

MASTER_SITES=		http://leafbsd.denpa.org/
DISTFILES=		xlvns1-1.6b.tar.gz

IS_INTERACTIVE=		No

USE_IMAKE=		Yes
USE_X11=		Yes

ALL_TARGET=		
INSTALL_TARGET=		???

.include <bsd.port.mk>
